version: '3.7'

services:
  backend:
    container_name: application
    image: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend_network
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=mks
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET=mks-challenge

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mks
    networks:
      - backend_network  
    volumes:
      - mks_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - backend_network  
    volumes:
      - mks_redis_data:/bitnami/redis/data

volumes:
  mks_pg_data:
  mks_redis_data:

networks:
  backend_network:
